//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebContactPage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Entry
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="First Name is required.")]
        [DisplayName("First Name")]
        public string firstName { get; set; }

        [Required(ErrorMessage = "Last Name is required.")]
        [DisplayName("Last Name")]
        public string lastName { get; set; }

        [Required(ErrorMessage = "Address is required.")]
        [DisplayName("Address")]
        public string address { get; set; }

        [Required(ErrorMessage = "Country is required.")]
        [DisplayName("Country")]
        public string country { get; set; }

        [Required(ErrorMessage = "Zip Code is required.")]
        [DisplayName("Zip Code")]
        public string zipCode { get; set; }

        [Required(ErrorMessage = "Phone Number is required.")]
        [DisplayName("Phone Number")]
        public string phoneNumber { get; set; }

        [Required(ErrorMessage = "Note is required.")]
        [DisplayName("Note")]
        [MaxLength(250, ErrorMessage ="Note must not exceed 250 characters.")]
        public string note { get; set; }
    }
}
